spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${LOCAL_DB_NAME}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-interval: 10s
          max-attempts: 3
          multiplier: 2

  elasticsearch:
    uris: ${ELASTICSEARCH_URIS}


  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
    elasticsearch:
      repositories:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

payment:
  client:
    key: ${PAYMENT_CLIENT_KEY}
  secret:
    key: ${PAYMENT_SECRET_KEY}

server:
  error:
    include-message: always

notification:
  related-url:
    auction: localhost:8080/api/v1/auctions/
    review: localhost:8080/api/v2/reviews/

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: TRACE