spring:
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]

cloud:
  aws:
    s3:
      bucket: ${S3_NAME}
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${S3_ACCESS}
      secret-key: ${S3_SECRET}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health"

  endpoint:
    health:
      show-details: always
  security:
    enabled: false

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
