spring:
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  application:
    name: auction-service

  cloud:
    openfeign:
      okhttp:
        enabled: true

cloud:
  aws:
    s3:
      bucket: ${S3_NAME}
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${S3_ACCESS}
      secret-key: ${S3_SECRET}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health"

  endpoint:
    health:
      show-details: always
  security:
    enabled: false

  health:
    eureka:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka

#  instance:
#    instance-id: ${spring.application.name}:localhost
#    prefer-ip-address: true


logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
    com.auction.feign.service.PointService: DEBUG

server:
  http2:
    enabled: true