spring:
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  application:
    name: auction-service

server:
  #  port: 8081
  port: 0   # 랜덤 포트

cloud:
  aws:
    s3:
      bucket: ${S3_NAME}
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${S3_ACCESS}
      secret-key: ${S3_SECRET}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health"

  endpoint:
    health:
      show-details: always
  security:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka