services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: elasticsearch
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data:/usr/share/elasticsearch/data
      - ./backup:/user/share/elasticsearch/backup
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
      - "ELASTIC_PASSWORD=000000"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - efk

networks:
  efk:
    driver: bridge